version: '3.8'

# Docker Compose đơn giản - chỉ bot và Lavalink
# Sử dụng khi bạn không cần database riêng

services:
  zkmusic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zkmusic-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./logs:/app/logs
      - ./database:/app/database
    networks:
      - zkmusic-network

  lavalink:
    image: fredboat/lavalink:4.0.8
    container_name: zkmusic-lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
    environment:
      - JAVA_OPTS=-Xmx1G -Xms512M
    networks:
      - zkmusic-network

networks:
  zkmusic-network:
    driver: bridge
