### Set Language command! ###
provide_lang_list: "<:wrong:1220876213896216686> **Invalid Language. Supported languages:**"
lang_set: "<:lang:1220885875773280316> **Language has been set to** `%{language}`"
lang_change: "<:lang:1220885875773280316> **Language has been changed to** `%{language}`"

### Prefix command! ###
prefix_arg: "<:wrong:1220876213896216686> Please provide a valid Prefix!"
prefix_length: "<:wrong:1220876213896216686> **Prefix can not be longer than 10 Characters**"
prefix_set: "<:magic:1220886110482468977> **Prefix has been set to** `%{prefix}`"
prefix_change: "<:magic:1220886110482468977> **Prefix has been changed to** `%{prefix}`"

### Setup Music Req command! ###
setup_arg_error: "<:wrong:1220876213896216686> Invalid! Please use %{text}"
setup_enable: "<:warnings:1220876158254710936> **Oops! Music System already exists.**"
setup_topic: "♪ Those who wish to sing always find a song. ♪"
setup_msg: "*`Succesfully Setup Music System in`* %{channel}\n```Note: Do not delete any message(s) I've created in order for me to work properly.```"
setup_null: "*`Successfully delete setup channel!`*"
setup_deleted: "*`Successfully delete setup channel!`*"
setup_queuemsg: "**Queue is empty**\n`Add songs to start listening`"
setup_playembed_author: "Now Playing"

### Reset Guild command! ###
### Reset User data command! ###

### Themes command!
error_themes: "<:wrong:1220876213896216686> Invalid... Please try again."
succes_themes: "**Succesfully changed theme to %{themes}**"

### Spotify Connect command!
spotify_connect_provide_id: "<:wrong:1220876213896216686> **Please provide a valid Spotify User ID**"
spotify_connect_success: "<:okee:1220876098456256512> **Successfully connected Spotify account!**"
spotify_connect_error: "<:wrong:1220876213896216686> **Error connecting Spotify account. Please try again later.**"

### Spotify Disconnect command!
spotify_disconnect_not_connected: "<:warnings:1220876158254710936> **You haven't connected any Spotify account**"
spotify_disconnect_success: "<:okee:1220876098456256512> **Successfully disconnected Spotify account!**"
spotify_disconnect_error: "<:wrong:1220876213896216686> **Error disconnecting Spotify account**"

### Spotify Feature Disabled!
spotify_feature_disabled_title: "Spotify Feature Disabled"
spotify_feature_disabled_desc: "Spotify feature is currently unavailable. Please try again later."

### Last FM Feature Disable!

### Notify Youtube Feature command!
### Notify Twitch Feature command!
### Temp Voice Feature command!
tempvoice_setup: "Temp Voice feature has been %{status}."
tempvoice_disabled: "Temp Voice has been disabled."
