# Database Service Language File (Vietnamese)

# Database connection messages
connection_failed: "Kết nối cơ sở dữ liệu thất bại"
connection_success: "Kết nối cơ sở dữ liệu thành công"
migration_start: "Bắt đầu migration cơ sở dữ liệu"
migration_complete: "Migration cơ sở dữ liệu hoàn tất"

# Task messages
premium_task_running: "Đang chạy tác vụ theo lịch cho người dùng và guild premium"
cleanup_task_running: "Đang chạy tác vụ theo lịch để xóa top tracks và top artists"
toptrack_cleared: "Đã xóa tất cả dữ liệu TopTrack."
topartist_cleared: "Đã xóa tất cả dữ liệu TopArtist."