### Lệnh đặt ngôn ngữ! ###
provide_lang_list: "<:wrong:1220876213896216686> **Ngôn ngữ không hợp lệ. Các ngôn ngữ được hỗ trợ:**"
lang_set: "<:lang:1220885875773280316> **Ngôn ngữ đã được đặt thành** `%{language}`"
lang_change: "<:lang:1220885875773280316> **Ngôn ngữ đã được chuyển sang** `%{language}`"

### Lệnh Prefix! ###
prefix_arg: "<:wrong:1220876213896216686> Vui lòng cung cấp Prefix hợp lệ!"
prefix_length: "<:wrong:1220876213896216686> **Prefix không được dài hơn 10 ký tự**"
prefix_set: "<:magic:1220886110482468977> **Prefix đã được đặt thành** `%{prefix}`"
prefix_change: "<:magic:1220886110482468977> **Prefix đã được thay đổi thành** `%{prefix}`"

### Lệnh thiết lập Music Req! ###
setup_arg_error: "<:wrong:1220876213896216686> Không hợp lệ! Vui lòng dùng %{text}"
setup_enable: "<:warnings:1220876158254710936> **Ồ! Hệ thống nhạc đã tồn tại.**"
setup_topic: "♪ Những ai muốn hát luôn tìm thấy bài ca. ♪"
setup_msg: "*`Thiết lập Hệ thống Nhạc thành công tại`* %{channel}\n```Lưu ý: Đừng xóa bất kỳ tin nhắn nào mình đã tạo để bot hoạt động đúng.```"
setup_null: "*`Đã xóa kênh thiết lập thành công!`*"
setup_deleted: "*`Đã xóa kênh thiết lập thành công!`*"

### Đặt lại dữ liệu máy chủ! ###
### Đặt lại dữ liệu người dùng! ###

### Lệnh chủ đề (Themes)!
error_themes: "<:wrong:1220876213896216686> Không hợp lệ... Vui lòng thử lại."
succes_themes: "**Đã đổi chủ đề thành %{themes} thành công**"

### Đăng nhập Last.fm!
lastfm_login_footer: "Lưu ý: Liên kết này sẽ hết hạn sau %{expired}."
lastfm_login_title: "Đăng nhập Last.fm"
lastfm_login_desc: "Bạn có muốn cấp quyền cho tài khoản [Last.fm](https://www.last.fm/user/romanromannya) của bạn không?\nNếu có, bấm nút bên dưới để bắt đầu quá trình xác thực."
lastfm_not_login_desc: "<:wrong:1220876213896216686> Bạn chưa đăng nhập Last.fm"

### Đăng xuất Last.fm!
lastfm_logout_title: "Đăng xuất Last.fm"
lastfm_logout_desc: "<:okee:1220876098456256512> Bạn đã đăng xuất khỏi Last.fm thành công"

### Tính năng Last.fm đang bị tắt!

### Kết nối Spotify!
### Ngắt kết nối Spotify!

### Tính năng Spotify Connect bị tắt!

### Thông báo YouTube!
### Thông báo Twitch!
### Tính năng Temp Voice!
tempvoice_setup: "Tính năng Temp Voice đã %{status}."
tempvoice_disabled: "Temp Voice đã bị tắt."
