import { AutoReconnect } from "./schema/AutoReconnect.js";
import { Playlist } from "./schema/Playlist.js";
import { Code } from "./schema/Code.js";
import { Premium } from "./schema/Premium.js";
import { Setup } from "./schema/Setup.js";
import { Language } from "./schema/Language.js";
import { Prefix } from "./schema/Prefix.js";
import { ControlButton } from "./schema/ControlButton.js";
import { QuickDatabasePlus } from "../structures/QuickDatabasePlus.js";
import { GuildPremium } from "./schema/GuildPremium.js";
import { BlacklistUser } from "./schema/BlacklistUser.js";
import { BlacklistGuild } from "./schema/BlacklistGuild.js";
import { Maintenance } from "./schema/Maintenanc.js";
import { Themes } from "./schema/Themes.js";
import { Votes } from "./schema/Votes.js";
import { CommandGlobalUsage } from "./schema/CommandGlobalUsage.js";
import { CommandUserUsage } from "./schema/CommandUserUsage.js";
import { PlayedSongUser } from "./schema/PlayedSongUser.js";
import { PlayedSongGuild } from "./schema/PlayedSongGuild.js";
import { PlayedSongGlobal } from "./schema/PlayedSongGlobal.js";
import { SpotifyId } from "./schema/SpotifyId.js";
import { VoteReminders } from "./schema/VoteReminders.js";
import { TopTrack } from "./schema/TopTrack.js";
import { TopArtist } from "./schema/TopArtist.js";
import { TempVoiceChannel } from "./schema/TempVoiceChannel.js";
import { TempVoiceChannelSetting } from "./schema/TempVoiceChannelSetting.js";
import { UserStatistics } from "./schema/UserStatistics.js";

export interface DatabaseTable {
  autoreconnect: QuickDatabasePlus<AutoReconnect>;
  playlist: QuickDatabasePlus<Playlist>;
  code: QuickDatabasePlus<Code>;
  premium: QuickDatabasePlus<Premium>;
  preGuild: QuickDatabasePlus<GuildPremium>;
  setup: QuickDatabasePlus<Setup>;
  language: QuickDatabasePlus<Language>;
  prefix: QuickDatabasePlus<Prefix>;
  ControlButton: QuickDatabasePlus<ControlButton>;
  BlacklistUser: QuickDatabasePlus<BlacklistUser>;
  BlacklistGuild: QuickDatabasePlus<BlacklistGuild>;
  maintenance: QuickDatabasePlus<Maintenance>;
  Themes: QuickDatabasePlus<Themes>;
  votes: QuickDatabasePlus<Votes>;
  CommandGlobalUsage: QuickDatabasePlus<CommandGlobalUsage>;
  CommandUserUsage: QuickDatabasePlus<CommandUserUsage>;
  PlayedSongUser: QuickDatabasePlus<PlayedSongUser>;
  PlayedSongGuild: QuickDatabasePlus<PlayedSongGuild>;
  PlayedSongGlobal: QuickDatabasePlus<PlayedSongGlobal>;
  SpotifyId: QuickDatabasePlus<SpotifyId>;
  VoteReminders: QuickDatabasePlus<VoteReminders>;
  TopTrack: QuickDatabasePlus<TopTrack>;
  TopArtist: QuickDatabasePlus<TopArtist>;
  TempVoiceChannel: QuickDatabasePlus<TempVoiceChannel>;
  TempVoiceChannelSetting: QuickDatabasePlus<TempVoiceChannelSetting>;
  UserStatistics: QuickDatabasePlus<UserStatistics>;
}
