### Set Language command! ###
provide_lang_list: "<:wrong:1220876213896216686> **Invalid Language. Supported languages:**"
lang_set: "<:lang:1220885875773280316> **Language has been set to** `%{language}`"
lang_change: "<:lang:1220885875773280316> **Language has been changed to** `%{language}`"

### Prefix command! ###
prefix_arg: "<:wrong:1220876213896216686> Please provide a valid Prefix!"
prefix_length: "<:wrong:1220876213896216686> **Prefix can not be longer than 10 Characters**"
prefix_set: "<:magic:1220886110482468977> **Prefix has been set to** `%{prefix}`"
prefix_change: "<:magic:1220886110482468977> **Prefix has been changed to** `%{prefix}`"

### Setup Music Req command! ###
setup_arg_error: "<:wrong:1220876213896216686> Invalid! Please use %{text}"
setup_enable: "<:warnings:1220876158254710936> **Oops! Music System already exists.**"
setup_topic: "♪ Those who wish to sing always find a song. ♪"
setup_msg: "*`Succesfully Setup Music System in`* %{channel}\n```Note: Do not delete any message(s) I've created in order for me to work properly.```"
setup_null: "*`Successfully delete setup channel!`*"
setup_deleted: "*`Successfully delete setup channel!`*"

### Reset Guild command! ###
### Reset User data command! ###

### Themes command!
error_themes: "<:wrong:1220876213896216686> Invalid... Please try again."
succes_themes: "**Succesfully changed theme to %{themes}**"

### Last FM Login command!
lastfm_login_footer: "Notes: This link will expire in %{expired}."
lastfm_login_title: "Last.fm Login"
lastfm_login_desc: "Would you like to grant authorization to your [Last.fm](https://www.last.fm/user/romanromannya) account?\nIf yes, please click the button below to start the authorization process."
lastfm_not_login_desc: "<:wrong:1220876213896216686> You are not logged in to Last.fm"

### Last FM Logout command!
lastfm_logout_title: "Last.fm Logout"
lastfm_logout_desc: "<:okee:1220876098456256512> You have successfully logout from Last.fm"

### Last FM Feature Disable!

### Spotify Connect command!
### Spotify Disconnect command!

### Last FM Feature Disable!

### Notify Youtube Feature command!
### Notify Twitch Feature command!
### Temp Voice Feature command!
tempvoice_setup: "Temp Voice feature has been %{status}."
tempvoice_disabled: "Temp Voice has been disabled."

# Additional settings keys
success_spotify: "Spotify settings updated successfully"
success_themes: "Theme changed successfully"
success_setup: "Setup completed successfully"
success_all_user: "All user settings updated successfully"
success_all_guild: "All guild settings updated successfully"
success_votes: "Vote settings updated successfully"
success_userstatistics: "User statistics settings updated successfully"
success_commandusage: "Command usage settings updated successfully"
success_lastfm: "Last.fm settings updated successfully"
success_twentyfourseven: "24/7 mode settings updated successfully"
success_playlist: "Playlist settings updated successfully"
success_tempvoice: "Temp voice settings updated successfully"
success_toptrack: "Top track settings updated successfully"
success_topartist: "Top artist settings updated successfully"
success_votereminder: "Vote reminder settings updated successfully"
success_prefix: "Prefix updated successfully"
success_playedsong: "Played song settings updated successfully"
title: "Settings"
no_permission: "You don't have permission to use this command"
reset_data: "Data has been reset successfully"
success_language: "Language settings updated successfully"
