lavalink:
    plugins:
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.4.2
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: com.dunctebot:skybot-lavalink-plugin:1.7.0
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: me.duncte123:java-lyrics-plugin:1.6.4
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: dev.lavalink.youtube:youtube-plugin:1.13.2
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: me.rohank05:lavalink-filter-plugin:0.0.4
          repository: https://jitpack.io
          snapshot: false
        - dependency: net.esmbot:lava-xm-plugin:0.2.5
          repository: https://repo.projectlounge.pw/maven/releases
          snapshot: false
        - dependency: com.github.ZenKho-chill:zk.icy.stream.lavalink:v1.0.9
          repository: https://jitpack.io
    pluginsDir: ./plugins
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 10
        password: youshallnotpass
        playerUpdateInterval: 5
        resamplingQuality: MEDIUM
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            mixer: true
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubeConfig:
            email: petitsorbetbot@gmail.com
            password: dX*%2!C7tWHUj%
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
        com.zenkho.icy: TRACE
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    icy:
        autoReconnect: true
        enableMetadata: true
        connectionTimeout: 10000
        readTimeout: 30000
        maxRetries: 3
        retryDelay: 2000
        followRedirects: true
    dunctebot:
        sources:
            clypit: true
            getyarn: true
            mixcloud: true
            ocremix: true
            pornhub: true
            reddit: true
            soundgasm: true
            tiktok: true
            tts: true
        ttsLanguage: en-US
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            mediaAPIToken: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldlYlBsYXlLaWQifQ.eyJpc3MiOiJBTVBXZWJQbGF5IiwiaWF0IjoxNzQxMTQxNzIzLCJleHAiOjE3NDgzOTkzMjMsInJvb3RfaHR0cHNfb3JpZ2luIjpbImFwcGxlLmNvbSJdfQ.XT0lXVrn9piwZqDhN9mb5z0bT7Bj1IGsGhbkA_UCqH6EBCJfhOTvYfheTAM3-EBqEIDo7xaPce_ZytzEOT4DyA
            playlistLoadLimit: 6
        deezer:
            arl: 2a54fa175023d763fbc0439b242fe05ce972ca9bff44a8e6aff633fe15dcf789c13ac5b960b2e684a7e89a91074aeccf0e3ace765ee964237da3390eba4cad4f18df38c0602bba12ac8c05ab142a55e9cc21a5cc153f580d697a505bad5613a9
            formats:
                - FLAC
                - MP3_320
                - MP3_256
                - MP3_128
                - MP3_64
                - AAC_64
            masterDecryptionKey: g4el58wc0zvf9na1
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
            - ytmsearch:"%ISRC%"
            - ytmsearch:%QUERY%
            - scsearch:%QUERY%
            - spsearch:%QUERY%
            - sprec:%QUERY%
            - amsearch:%QUERY%
            - dzisrc:%ISRC%
            - dzrec:%QUERY%
            - dzsearch:%QUERY%
            - tdsearch:%QUERY%
        sources:
            applemusic: true
            deezer: true
            flowerytts: true
            spotify: true
            tidal: true
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 6
            clientId: d4c8c0fb4792413594e8ba463eedfc52
            clientSecret: d29fa7d2ea234f858aabf68af3803b85
            countryCode: US
            localFiles: false
            playlistLoadLimit: 6
            resolveArtistsInSearch: true
        tidal:
            countryCode: US
            searchLimit: 6
        youtube:
            countryCode: US
    xm:
        amigaMixer: false
        ampFactor: 1
        fixSampleLoop: false
        fx9Bug: false
        interpolation: 1
        vblank: false
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clients:
            - MUSIC
            - TVHTML5EMBEDDED
            - MWEB
            - WEBEMBEDDED
            - ANDROID_VR
            - TV
            - IOS
            - TVHTML5EMBEDDED
        enabled: true
        oauth:
            enabled: true
            refreshToken: 1//04_onXJojd-hRCgYIARAAGAQSNwF-L9Irjg5Hb1NK6TGj58ZBSldIobgzd6aGaG1Trq2wsU2Ze5SMv4D7DqDlkKet99XKyRR7zFs
            skipInitialization: true
        pot:
            token: MngIt-aAnc1pIAiLkoAA6fbtcz9JwjBgnA0UqkPbiJI8sg8l34z_V4ndFkSogvvwBdP-jqONyoCX3cHFEZwVlHoE1ZGNuv9LvJLqaBEp5uP5qAI_tw9-gI60GrI1dVW95249cFkCLx8eAmsj3KBSpJZU5ZF3acrHc2U=
            visitorData: Cgt4V0NlNFgxLXMyMCjgsLS6BjIKCgJJRBIEGgAgWg%3D%3D
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: true
    port: 2333
